import Head from "next/head";
import Image from "next/image";
import allPhotos from "../assets/All_photos.png"
import food from "../assets/food.png"
import venue from "../assets/venue.png"
import events from "../assets/events.png"
import images from "../utils/images.json"

import Navbar from '@/components/navbar'
import styles from "../styles/gallery.module.css";

const renderImages1 = () => {
    const firstImage = images.imageList[0];

    return (
        <div className={styles.container}>
            <div>
                <img src={firstImage.url} alt="event image" className={styles.largeImage} />
            </div>
            <div className={styles.small_image_column}>
                <div className={styles.row}>
                    {images.imageList.slice(1, 3).map((image, index) => (
                        <div key={index} className={styles.gallery_content}>
                            <img src={image.url} alt="event image" />
                        </div>
                    ))}
                </div>
                <div className={styles.row}>
                    {images.imageList.slice(3, 5).map((image, index) => (
                        <div key={index} className={styles.gallery_content}>
                            <img src={image.url} alt="event image" style={{ width: "100%", height: "100%" }} />
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};

const renderImages2 = () => {
    const lastImage = images.imageList[9];

    return (
        <div className={styles.container}>

            <div className={styles.small_image_column}>
                <div className={styles.row}>
                    {images.imageList.slice(5, 7).map((image, index) => (
                        <div key={index} className={styles.gallery_content}>
                            <img src={image.url} alt="event image" className={styles.smallImage} style={{ width: "100%", height: "100%" }} />
                        </div>
                    ))}
                </div>
                <div className={styles.row}>
                    {images.imageList.slice(7, 9).map((image, index) => (
                        <div key={index} className={styles.gallery_content}>
                            <img src={image.url} alt="event image" className={styles.smallImage} style={{ width: "100%", height: "100%" }} />
                        </div>
                    ))}
                </div>
            </div>
            <div >
                <img src={lastImage.url} alt="event image" className={styles.largeImage} />
            </div>
        </div>
    );
};



export default function gallery() {


    return (
        <>
            <Head>
                <title>Gallery</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />

                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Alike&family=Poppins:wght@100;200;300;500&family=Roboto:wght@100;700&display=swap" rel="stylesheet"></link>
            </Head>
            <Navbar />
            <main className={styles.main}>
                <div className={styles.header_section}>
                    <div className={styles.header_items}>

                        <Image
                            src={allPhotos}
                            height={30}
                            width={30}
                            alt="All photos"
                        />
                        <h4>All Photos</h4>

                    </div>
                    <div className={styles.header_items}>
                        <Image
                            src={venue}
                            height={30}
                            width={30}
                            alt="Venue Icon"
                        />
                        <h4>Venue</h4>
                    </div>
                    <div className={styles.header_items}>
                        <Image
                            src={events}
                            height={30}
                            width={30}
                            alt="Events Icon"
                        />
                        <h4>Events</h4>
                    </div>
                    <div className={styles.header_items}>
                        <Image
                            src={food}
                            height={30}
                            width={30}
                            alt="Food Icon"
                        />
                        <h4>Food</h4>
                    </div>

                </div>
                {/* <div className={styles.container}>
                    {renderImages()}
                </div> */}
                {renderImages1()}
                {renderImages2()}
                {renderImages1()}
                {renderImages2()}
            </main>
        </>
    );
}

