import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import arrow from "../assets/arrow_right.png"
import Link from 'next/link'

import Navbar from '@/components/navbar'

import EventCard from '@/components/card'
import eventData from "../utils/data.json"

import { useState } from 'react'

export default function Home() {

  const [numCardsToShow, setNumCardsToShow] = useState(6);

  const handleSeeMoreClick = () => {
    setNumCardsToShow(numCardsToShow + 6);
  };

  const [query, setQuery] = useState('');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Alike&family=Poppins:wght@100;200;300;500&family=Roboto:wght@100;700&display=swap" rel="stylesheet"></link>
      </Head>
      <Navbar query={query} setQuery={setQuery} />
      <main className={styles.main}>

        <div className={styles.head_section}>
          <div className={styles.head_description}>
            <span className={styles.head_description1}>The perfect night out in Glasgow !</span>
            <span className={styles.head_description2}>18 Candleriggs</span>
          </div>

        </div>

        <div className={styles.eventlist_heading}>
          <div className={styles.eventlist_heading_item1}>
            <span>What's On At Glasgow's Coolest Event Space.</span>
          </div>
          <div className={styles.eventlist_heading_item2}>
            <div>
              <Link href="/"><h3>View all</h3></Link>
            </div>
            <div>
              <Image
                src={arrow}
                height={13}
                width={18}
                alt="arrow image"
              /></div>
          </div>
        </div>
        <div className={styles.event_list}>

          {eventData.events && eventData.events.length ? eventData.events.filter((item) => {
            if (query === "") {
              return item;
            } else if (
              item.name
                .toLowerCase()
                .includes(query.toLowerCase())
            ) {
              return item;
            }
          }).slice(0, numCardsToShow).map((event) => (
            <EventCard key={event.id} event={event} />
          )) : <div> No data to display</div>}
        </div>
        <div >
          <button className={styles.more_events} onClick={handleSeeMoreClick}>More Events</button>
        </div>

      </main>
    </>
  );
}
